## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
        
    obj = bld.create_ns3_program('test', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'test.cc'

    obj = bld.create_ns3_program('topology-reader', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'topology-reader.cc'
