#!/bin/bash
python traffic-test.py ../../topos/2914.bb.new 50 "(1,12)" 0 500 3 "(0.0,0.1,0.1)" ../../results-cameraready/latency/2914.1-12.50 10.0
python traffic-test.py ../../topos/7018.bb 50 "(1,12)" 0 500 3 "(0.0,0.1,0.1)" ../../results-cameraready/latency/7018.1-12.50 10.0
python traffic-test.py ../../topos/1239.bb  50 "(1,12)" 0 500 3 "(0.0,0.1,0.1)" ../../results-cameraready/latency/1239.1-12.50 10.0
python traffic-test.py ../../topos/FatTree_8.topo 50 "(1,12)" 0 500 3 "(0.0,0.1,0.1)" ../../results-cameraready/latency/FatTree.1-12.50 0.25
python traffic-test.py ../../topos/3tier_4_4x2_4x16.topo 50 "(1,12)" 0 500 3 "(0.0,0.1,0.1)" ../../results-cameraready/latency/3tier.1-12.50 0.25
