## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
        
    obj = bld.create_ns3_program('test', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'test.cc'
#
    obj = bld.create_ns3_program('topology-reader', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'topology-reader.cc'
#
    obj = bld.create_ns3_program('stretch', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'stretch.cc'

    obj = bld.create_ns3_program('tcp-burst', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'tcp-burst.cc'

    obj = bld.create_ns3_program('traffic-sim', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'traffic-sim.cc'

    obj = bld.create_ns3_program('traffic-sim-latency', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'traffic-sim-latency.cc'

    obj = bld.create_ns3_program('traffic-sim-random', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'traffic-sim-latency-random.cc'

    obj = bld.create_ns3_program('traffic-sim-tcp', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'traffic-sim-tcp.cc'

    obj = bld.create_ns3_program('traffic-sim-tcp-noreversal', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'traffic-sim-tcp-noreversal.cc'

    obj = bld.create_ns3_program('partition-aggregate-test', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'partition-aggregate-test.cc'

    obj = bld.create_ns3_program('wan-bulk-transfer', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
    obj.source = 'wan-bulk-transfer.cc'
#
#    obj = bld.create_ns3_program('stretch-sp', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
#    obj.source = 'stretch-sp.cc'
#
#    obj = bld.create_ns3_program('scope', ['core', 'point-to-point', 'internet', 'applications', 'olsr'])
#    obj.source = 'scope.cc'
